# Generated by Django 2.2.5 on 2019-12-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20191117_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='users',
            new_name='user',
        ),
    ]
